package com.lidarscan.core.calib

import kotlin.math.abs
import kotlin.math.roundToInt

/**
 * One prescribed viewpoint the wizard asks the user to reproduce.
 *
 * The sweep is WIZARD.md screen 2's, verbatim: azimuth −38°…+38°, elevation
 * −24°…+26°, **roll −60°…+60°** — "the same sequence the simulation uses,
 * which is why its numbers apply". Roll is the load-bearing axis: S6 finding 3
 * measured that poses varying only in position roughly DOUBLE the error
 * (Mid-360 4.5 px → 8.7 px; D6 34.6 px → 80.0 px), because the D6's scan-line
 * direction across the target changes only when the phone rolls.
 */
data class PrescribedPose(
    val index: Int,
    val azimuthDeg: Double,
    val elevationDeg: Double,
    val rollDeg: Double,
)

/**
 * The prescribed sequence. Generated by a **low-discrepancy (additive
 * recurrence / golden-ratio) sweep** rather than a random draw or a regular
 * grid: a random draw can clump and leave a whole octant of roll unvisited on
 * a short 8-pose session, and a regular grid in three axes needs 27 poses to
 * say anything, which is over the two-minute budget. The additive recurrence
 * fills each axis evenly for *any* prefix length, which is what makes
 * "stopping at 8" and "stopping at 12" both well-conditioned.
 */
object PosePlan {

    private const val AZIMUTH_MIN = -38.0
    private const val AZIMUTH_MAX = 38.0
    private const val ELEVATION_MIN = -24.0
    private const val ELEVATION_MAX = 26.0
    private const val ROLL_MIN = -60.0
    private const val ROLL_MAX = 60.0

    // Three mutually irrational-ish increments (the golden ratio and two of
    // its plastic-number cousins), so the three axes do not lock into a
    // repeating pattern with each other.
    private const val PHI_1 = 0.6180339887498949
    private const val PHI_2 = 0.7548776662466927
    private const val PHI_3 = 0.5698402909980532

    fun poses(count: Int): List<PrescribedPose> = (0 until count).map { i ->
        val u = ((i + 1) * PHI_1) % 1.0
        val v = ((i + 1) * PHI_2) % 1.0
        val w = ((i + 1) * PHI_3) % 1.0
        PrescribedPose(
            index = i,
            azimuthDeg = AZIMUTH_MIN + u * (AZIMUTH_MAX - AZIMUTH_MIN),
            elevationDeg = ELEVATION_MIN + v * (ELEVATION_MAX - ELEVATION_MIN),
            // Alternate the sign so consecutive prompts ask for opposite
            // tilts — a user who is drifting toward "always tilt right"
            // notices immediately.
            rollDeg = (if (i % 2 == 0) 1.0 else -1.0) * (ROLL_MIN + w * (ROLL_MAX - ROLL_MIN)).let { abs(it) }
                .coerceAtMost(ROLL_MAX),
        )
    }

    /** WIZARD.md §1: 8 for the Mid-360 (5 acceptable, 12 no better), 12 for the D6 (and still not enough — see the bench note). */
    fun recommendedCount(profile: LidarProfile): Int = profile.recommendedPoses
}

/**
 * WIZARD.md screen 2's **pose-diversity wheel**: "a 3-axis dial showing which
 * regions of the azimuth/elevation/roll space have been covered… This makes
 * 'you have 8 samples but they are all the same view' visible, which a bare
 * '6 / 8' cannot."
 *
 * Each axis is bucketed into [BUCKETS] bins over its prescribed range; a
 * bucket is "covered" once any captured pose lands in it. [coverage] is the
 * fraction of buckets covered across all three axes, and [weakestAxis] is
 * what the reject screen's diagnosis reads to say "tilt the phone more
 * between shots".
 */
class DiversityWheel(private val buckets: Int = BUCKETS) {

    private val azimuth = BooleanArray(buckets)
    private val elevation = BooleanArray(buckets)
    private val roll = BooleanArray(buckets)

    fun add(azimuthDeg: Double, elevationDeg: Double, rollDeg: Double) {
        azimuth[bucketOf(azimuthDeg, -38.0, 38.0)] = true
        elevation[bucketOf(elevationDeg, -24.0, 26.0)] = true
        roll[bucketOf(rollDeg, -60.0, 60.0)] = true
    }

    fun axisCoverage(): Triple<Double, Double, Double> = Triple(
        azimuth.count { it }.toDouble() / buckets,
        elevation.count { it }.toDouble() / buckets,
        roll.count { it }.toDouble() / buckets,
    )

    val coverage: Double
        get() {
            val (a, e, r) = axisCoverage()
            return (a + e + r) / 3.0
        }

    /** Which axis is least covered — the one the user should be told to vary. */
    fun weakestAxis(): Axis {
        val (a, e, r) = axisCoverage()
        return when (minOf(a, e, r)) {
            r -> Axis.ROLL
            e -> Axis.ELEVATION
            else -> Axis.AZIMUTH
        }
    }

    fun bucketsFor(axis: Axis): BooleanArray = when (axis) {
        Axis.AZIMUTH -> azimuth.copyOf()
        Axis.ELEVATION -> elevation.copyOf()
        Axis.ROLL -> roll.copyOf()
    }

    private fun bucketOf(value: Double, min: Double, max: Double): Int {
        val t = ((value - min) / (max - min)).coerceIn(0.0, 0.999999)
        return (t * buckets).toInt().coerceIn(0, buckets - 1)
    }

    enum class Axis { AZIMUTH, ELEVATION, ROLL }

    companion object {
        const val BUCKETS = 6
    }
}

/** Rounds a degree value for display without pretending to sub-degree accuracy the user could act on. */
fun formatDegrees(value: Double): String = "${value.roundToInt()}°"
