#!/usr/bin/env bash
# C1 verification run — the app producing its own evidence.
#
# Every artefact under evidence/ is generated by this script:
#   synth-d6.bin              engine_cli --synth: 30 s of synthetic COIN-D6 wire
#                             bytes, including the 0xFE/0xFF speed-adjustment and
#                             garbage traffic --noise injects
#   synth.lscan/              a real .lscan written by the ENGINE's FileRecordWriter,
#                             via Engine::push_serial_bytes() — the same entry
#                             point a live USB serial reader uses
#   01-replay-full.png        the cloud after an unpaced replay of the whole capture
#   02-replay-midway.png      a paced (4x) replay caught mid-stream — fewer points,
#                             which is the proof the viewport is streaming and not
#                             showing a preloaded cloud
#   03-display-params.png     the same cloud under a different A14 DisplayParams
#                             document (intensity + thermal colormap)
#   04-resize-storm.png       after S3's continuous-resize stress
#   05-hidpi-dpr2.png         the same scene at devicePixelRatio 2.0
#   *-qtchrome.png            QWidget::grab() of the window: the 3D area is EMPTY,
#                             which is itself the proof the viewport is a native
#                             child window and not something Qt painted
#   *-window.png              the two composited — what the user sees
#   verify.log                everything below, verbatim
#
# Screenshots come from Renderer::readPixels() off the swapchain (S3 REPORT §6):
# strictly better provenance than an OS screen capture, and it works in a shell
# with no Screen Recording permission.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD="${HERE}/build"
OUT="${HERE}/evidence"
APP="${BUILD}/lidarscan"
CLI="${BUILD}/engine/engine_cli"

mkdir -p "$OUT"
LOG="${OUT}/verify.log"
: > "$LOG"

run() { echo "\$ $*" | tee -a "$LOG"; "$@" 2>&1 | tee -a "$LOG"; }

echo "=== 0. toolchain ===" | tee -a "$LOG"
run cmake --version
run "$CLI" --version

echo "=== 1. synthetic COIN-D6 capture (S1 packet builder, via engine_cli) ===" | tee -a "$LOG"
run "$CLI" --synth "${OUT}/synth-d6.bin" 30 --noise

echo "=== 2. import into a .lscan + unpaced replay + screenshot ===" | tee -a "$LOG"
rm -rf "${OUT}/synth.lscan"
run "$APP" --project "${OUT}/synth.lscan" --import-raw "${OUT}/synth-d6.bin" \
    --replay=0 --shot "${OUT}/01-replay-full.png" --shot-delay 6 --quit-after 9

echo "=== 3. paced replay, screenshot taken MID-STREAM ===" | tee -a "$LOG"
run "$APP" --project "${OUT}/synth.lscan" --replay=4 \
    --shot "${OUT}/02-replay-midway.png" --shot-delay 3.5 --quit-after 7

# Display parameters, loaded through A14's own from_json(). Intensity colour
# mode + the thermal colormap + an explicit range: the same cloud as step 2,
# rendered completely differently, which is what proves the DisplayParams ->
# DisplayParamsUniforms -> Filament MaterialInstance binding is live rather than
# decorative.
#
# A named profile is NOT used here. `floorPlan` enables a 1.0-1.5 m height clip
# band and a COIN-D6 scan is a single horizontal plane at z = 0, so that profile
# correctly renders NOTHING for this data; `research` selects ColorMode::kRgb,
# and the D6's authored colour is its raw intensity byte (~25/255 at these
# ranges), i.e. near-black and correct but invisible. Both are faithful; neither
# makes a useful screenshot.
echo "=== 4. display parameters via A14 from_json (intensity + thermal) ===" | tee -a "$LOG"
run "$APP" --project "${OUT}/synth.lscan" --replay=0 \
    --display-params "${HERE}/scripts/display-params-intensity.json" \
    --shot "${OUT}/03-display-params.png" --shot-delay 6 --quit-after 9

echo "=== 5. resize storm (S3 stability stress, productionized path) ===" | tee -a "$LOG"
run "$APP" --project "${OUT}/synth.lscan" --replay=0 --resize-storm 10 \
    --shot "${OUT}/04-resize-storm.png" --shot-delay 12 --quit-after 15

echo "=== 6. HiDPI: the same run at devicePixelRatio 2.0 ===" | tee -a "$LOG"
echo "\$ QT_SCALE_FACTOR=2 $APP ..." | tee -a "$LOG"
QT_SCALE_FACTOR=2 "$APP" --project "${OUT}/synth.lscan" --replay=0 \
    --display-params "${HERE}/scripts/display-params-intensity.json" \
    --shot "${OUT}/05-hidpi-dpr2.png" --shot-delay 6 --quit-after 9 2>&1 | tee -a "$LOG"

echo "=== 7. .lscan re-read after everything ===" | tee -a "$LOG"
run find "${OUT}/synth.lscan" -type f -exec ls -la {} +

echo "verification complete — see ${OUT}" | tee -a "$LOG"
