// test_e2_replay_golden.cpp — E2: replay/golden integration tests.
//
// Owner: E2 (Tech Spec §4 workstream E). Lives in engine/tests/ (NOT
// engine/tests/integration/) so CMakeLists.txt's `file(GLOB tests/test_*.cpp)`
// picks it up with no CMakeLists.txt edit — see engine/tests/integration/data/
// README.md for why the fixture *data* still lives under integration/.
//
// Three things, in order of how much ground truth they have:
//
//  1. A committed golden COIN-D6 byte stream, decoded through the real
//     D6Driver, asserted against hand-verified point count / checksum stats /
//     first+last point coordinates. The bytes never change; a decode
//     regression is a value regression here, not a "did the file change" diff.
//  2. The same idea for a synthetic Livox Mid-360 datagram sequence, decoded
//     through the real Mid360Driver (kInject backend — no socket, no SDK).
//  3. IF the CC-BY real Mid-360 capture (spikes/s2-mid360-sim/fixtures/
//     outdoor_imu_ccby_6s.livoxdump, committed, §per FIXTURES.md) is present,
//     an end-to-end LIO+post determinism test over it, checked against the
//     numbers docs/A6-lio.md §7.2 and docs/A7-post.md §6.3 measured on the
//     same file: path length ~32.4 m, |g| ~9.816 m/s². This is a RUNTIME
//     existence check (std::fopen), not a doctest::skip() tag, and not a
//     CMakeLists.txt change — same pattern test_lio.cpp/test_post.cpp use for
//     the same fixture, kept independent here rather than reusing their
//     anonymous-namespace helpers.
//
// --- regenerating the committed golden fixtures ----------------------------
//
// tests/integration/data/golden_d6.bin and golden_mid360.bin are generated by
// this file's own "e2/regenerate_golden_fixtures" case, which is a no-op
// unless SCANENGINE_REGEN_GOLDEN is set — it is never run by a normal `ctest`
// or `scanengine_tests` invocation, only by hand:
//
//   cmake --build build --target scanengine_tests
//   SCANENGINE_REGEN_GOLDEN=1 \
//     ./build/scanengine_tests --test-case="e2/regenerate_golden_fixtures"
//
// Both builders (d6test::build_revolution and this file's mid360 packet
// helpers) are fully deterministic, so regenerating reproduces byte-identical
// files unless the builder itself changed — which is exactly the case where
// regenerating and re-committing is the right thing to do.
#include <atomic>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

#include "doctest.h"
#include "packet_builder.h"  // d6test:: — the S1 packet builder, shared with test_d6_*.cpp
#include "scanengine/cloud/page_store.h"
#include "scanengine/core/error.h"
#include "scanengine/core/event_bus.h"
#include "scanengine/drivers/d6/d6_driver.h"
#include "scanengine/drivers/mid360/mid360_driver.h"
#include "scanengine/drivers/mid360/mid360_packets.h"
#include "scanengine/record/lscan.h"
#include "scanengine/slam/post/post_pipeline.h"

using namespace scanengine;

namespace {

// --- path helpers -----------------------------------------------------------
//
// __FILE__-relative, same technique test_lio.cpp/test_post.cpp use for the
// livoxdump fixture: no CMakeLists.txt variable needed, works from any CWD a
// developer or CI runs `ctest`/`scanengine_tests` from.
std::string repo_root_from_this_file() {
  std::string here = __FILE__;  // .../engine/tests/test_e2_replay_golden.cpp
  // MSVC's __FILE__ uses backslashes, which made the separator-sensitive
  // rfind miss and sent Windows to a CWD-relative path that ctest does not
  // run from (engine-ci #5) — normalize first.
  for (char& c : here) {
    if (c == '\\') c = '/';
  }
  const std::size_t cut = here.rfind("engine/tests/");
  return cut != std::string::npos ? here.substr(0, cut) : std::string();
}

std::string data_path(const char* filename) {
  const std::string root = repo_root_from_this_file();
  if (!root.empty()) return root + "engine/tests/integration/data/" + filename;
  return std::string("tests/integration/data/") + filename;  // CWD == engine/
}

std::string find_ccby_fixture() {
  if (const char* env = std::getenv("SCANENGINE_LIVOXDUMP")) {
    if (env[0] != '\0') return env;
  }
  const std::string root = repo_root_from_this_file();
  const char* rel = "spikes/s2-mid360-sim/fixtures/outdoor_imu_ccby_6s.livoxdump";
  if (!root.empty()) {
    const std::string cand = root + rel;
    if (std::FILE* f = std::fopen(cand.c_str(), "rb")) {
      std::fclose(f);
      return cand;
    }
  }
  const char* ups[] = {"", "../", "../../", "../../../", "../../../../"};
  for (const char* up : ups) {
    const std::string cand = std::string(up) + rel;
    if (std::FILE* f = std::fopen(cand.c_str(), "rb")) {
      std::fclose(f);
      return cand;
    }
  }
  return std::string();
}

bool write_file(const std::string& path, const std::vector<std::uint8_t>& bytes) {
  std::ofstream f(path, std::ios::binary | std::ios::trunc);
  if (!f) return false;
  f.write(reinterpret_cast<const char*>(bytes.data()),
          static_cast<std::streamsize>(bytes.size()));
  return f.good();
}

bool read_file(const std::string& path, std::vector<std::uint8_t>* out) {
  std::ifstream f(path, std::ios::binary | std::ios::ate);
  if (!f) return false;
  const std::streamsize n = f.tellg();
  if (n < 0) return false;
  out->resize(static_cast<std::size_t>(n));
  f.seekg(0);
  f.read(reinterpret_cast<char*>(out->data()), n);
  return f.good();
}

// --- the D6 golden byte stream ----------------------------------------------
//
// One start packet (angle 0, the S1/vendor convention) + 6 data packets of 20
// samples each swept evenly over 360 deg, constant range (1.000 m) and
// intensity (128) — build_revolution() is the exact S1 packet builder every
// D6 unit test in this repo already trusts (packet_builder.h, shared with
// test_d6_driver.cpp/test_d6_parser.cpp). 433 bytes total: tiny, and every
// byte in it is a function of the four literals below, so a curious reader
// can recompute it by hand.
std::vector<std::uint8_t> build_golden_d6_bytes() {
  return d6test::build_revolution(/*packets=*/6, /*per_packet=*/20,
                                   /*distance_mm=*/1000, /*intensity=*/128,
                                   /*scan_freq=*/10);
}

// --- the Mid-360 golden datagram sequence -----------------------------------
//
// Raw wire bytes, exactly as Mid360Driver::on_point_packet/on_imu_packet
// consume them (kInject backend) or as they'd arrive off the real UDP ports —
// self-delimiting via DataHeader::length, so the golden file needs no
// container framing of its own. Mirrors test_mid360_driver.cpp's
// make_point_packet/make_imu_packet/fix_crc helpers (kept independent here,
// per the ownership split: this file does not include test_mid360_driver.cpp).
using mid360::CartesianHigh;
using mid360::DataHeader;
using mid360::ImuRaw;

void fix_crc(std::vector<std::uint8_t>* b) {
  auto* h = reinterpret_cast<DataHeader*>(b->data());
  h->crc32 = mid360::crc32_iso_hdlc(b->data() + offsetof(DataHeader, timestamp),
                                     b->size() - offsetof(DataHeader, timestamp));
}

std::vector<std::uint8_t> build_point_packet(std::uint16_t udp_cnt, std::uint16_t dot_num,
                                             std::int32_t x0) {
  std::vector<std::uint8_t> b(sizeof(DataHeader) + dot_num * sizeof(CartesianHigh), 0);
  auto* h = reinterpret_cast<DataHeader*>(b.data());
  h->version = 0;
  h->length = static_cast<std::uint16_t>(b.size());
  h->time_interval = 4750;
  h->dot_num = dot_num;
  h->udp_cnt = udp_cnt;
  h->frame_cnt = 0;
  h->data_type = mid360::kDataTypeCartesianHigh;
  h->time_type = 0;
  h->timestamp = 2'000'000'000ULL + static_cast<std::uint64_t>(udp_cnt) * 480'000ULL;
  auto* pts = reinterpret_cast<CartesianHigh*>(b.data() + sizeof(DataHeader));
  for (std::uint16_t i = 0; i < dot_num; ++i) {
    pts[i].x = x0 + static_cast<std::int32_t>(i) * 10;  // millimetres
    pts[i].y = 3000;
    pts[i].z = 1200;
    pts[i].reflectivity = static_cast<std::uint8_t>(50 + (i % 100));
    pts[i].tag = 0;
  }
  fix_crc(&b);
  return b;
}

std::vector<std::uint8_t> build_imu_packet(std::uint16_t udp_cnt, float gyro_x, float acc_z) {
  std::vector<std::uint8_t> b(sizeof(DataHeader) + sizeof(ImuRaw), 0);
  auto* h = reinterpret_cast<DataHeader*>(b.data());
  h->version = 0;
  h->length = static_cast<std::uint16_t>(b.size());
  h->dot_num = 1;
  h->udp_cnt = udp_cnt;
  h->data_type = mid360::kDataTypeImu;
  h->time_type = 0;
  h->timestamp = 2'000'000'000ULL + static_cast<std::uint64_t>(udp_cnt) * 5'000'000ULL;
  auto* s = reinterpret_cast<ImuRaw*>(b.data() + sizeof(DataHeader));
  s->gyro_x = gyro_x;
  s->gyro_y = 0.f;
  s->gyro_z = 0.f;
  s->acc_x = 0.f;
  s->acc_y = 0.f;
  s->acc_z = acc_z;
  fix_crc(&b);
  return b;
}

// 8 point packets (96 pts each = 768 points) with 2 IMU samples interleaved —
// small (8*1380 + 2*60 = 11,160 bytes), deterministic, every point passes the
// default filter (tag 0, non-zero, in range) so kept == received.
std::vector<std::uint8_t> build_golden_mid360_bytes() {
  std::vector<std::uint8_t> out;
  auto append = [&](const std::vector<std::uint8_t>& b) {
    out.insert(out.end(), b.begin(), b.end());
  };
  for (std::uint16_t k = 0; k < 4; ++k) {
    append(build_point_packet(k, mid360::kPointsPerPacket, 1000 + k * 100));
  }
  append(build_imu_packet(0, 0.01f, 1.0f));
  for (std::uint16_t k = 4; k < 8; ++k) {
    append(build_point_packet(k, mid360::kPointsPerPacket, 1000 + k * 100));
  }
  append(build_imu_packet(1, -0.02f, 0.98f));
  return out;
}

// Walk a concatenated sequence of raw Mid-360 datagrams, one push per
// datagram, exactly the shape the kInject backend / a live UDP recvfrom loop
// hands the driver. Returns false on any framing inconsistency (there should
// be none — the golden file is self-consistent by construction).
bool feed_mid360_datagrams(Mid360Driver* driver, const std::vector<std::uint8_t>& bytes,
                           TimePoint t, std::size_t* datagrams_out) {
  std::size_t off = 0, n = 0;
  while (off + sizeof(DataHeader) <= bytes.size()) {
    std::uint16_t length = 0;
    std::memcpy(&length, bytes.data() + off + offsetof(DataHeader, length), sizeof(length));
    if (length < sizeof(DataHeader) || off + length > bytes.size()) return false;
    const std::uint8_t data_type = bytes[off + offsetof(DataHeader, data_type)];
    if (data_type == mid360::kDataTypeImu) {
      driver->on_imu_packet(bytes.data() + off, length, t);
    } else {
      driver->on_point_packet(bytes.data() + off, length, t);
    }
    off += length;
    ++n;
  }
  *datagrams_out = n;
  return off == bytes.size();
}

// --- CC-BY real-capture transcode (independent copy of the test_post.cpp
// helper of the same shape — see that file's "real_mid360_capture" case;
// duplicated rather than shared because the two files are owned by different
// waves this round and neither includes the other's anonymous namespace) ---

bool transcode_livoxdump(const std::string& src, const std::string& dst, std::uint64_t* records) {
  std::FILE* f = std::fopen(src.c_str(), "rb");
  if (f == nullptr) return false;
  auto rd = [&](void* p, std::size_t n) { return std::fread(p, 1, n, f) == n; };
  char magic[8];
  std::uint16_t version = 0, num_ports = 0;
  if (!rd(magic, 8) || std::memcmp(magic, "LX360CAP", 8) != 0 || !rd(&version, 2) ||
      !rd(&num_ports, 2) || num_ports == 0 || num_ports > 16) {
    std::fclose(f);
    return false;
  }
  std::vector<std::uint32_t> ports(num_ports);
  if (!rd(ports.data(), 4u * num_ports)) {
    std::fclose(f);
    return false;
  }
  lscan::FileRecordWriter w;
  if (!w.open(dst).ok()) {
    std::fclose(f);
    return false;
  }
  std::vector<std::uint8_t> payload;
  std::uint64_t n = 0;
  for (;;) {
    std::uint64_t t = 0;
    std::uint16_t idx = 0;
    std::uint32_t len = 0;
    if (!rd(&t, 8) || !rd(&idx, 2) || !rd(&len, 4)) break;
    if (idx >= num_ports || len > 65535) break;
    payload.resize(len);
    if (len != 0 && !rd(payload.data(), len)) break;
    const mid360::PacketView v = mid360::parse_packet(payload.data(), payload.size());
    if (!v.valid()) continue;
    const lscan::ChunkType ct = v.header->data_type == mid360::kDataTypeImu
                                    ? lscan::ChunkType::kMid360Imu
                                    : lscan::ChunkType::kMid360Points;
    if (!w.write_chunk(ct, static_cast<std::int64_t>(t), ByteSpan(payload.data(), payload.size()))
             .ok()) {
      break;
    }
    ++n;
  }
  std::fclose(f);
  (void)w.close();  // best-effort: a close failure here would already have
                     // surfaced as a write_chunk() failure above.
  if (records != nullptr) *records = n;
  return n > 0;
}

// Same shape as test_post.cpp's make_temp_dir/TempDirGuard (portable via
// std::filesystem rather than platform-specific mkdtemp/_mkdir; kept as an
// independent copy per the ownership split noted above the transcode helper).
std::string make_temp_dir(const char* tag) {
  static std::atomic<long long> counter{0};
  const auto id = counter.fetch_add(1, std::memory_order_relaxed);
  const auto now = std::chrono::steady_clock::now().time_since_epoch().count();
  const std::filesystem::path p =
      std::filesystem::temp_directory_path() /
      (std::string("e2_test_") + tag + "_" + std::to_string(now) + "_" + std::to_string(id));
  std::error_code ec;
  std::filesystem::remove_all(p, ec);
  return p.string();
}

struct TempDirGuard {
  std::string dir;
  explicit TempDirGuard(std::string d) : dir(std::move(d)) {}
  ~TempDirGuard() {
    std::error_code ec;
    std::filesystem::remove_all(dir, ec);
  }
  TempDirGuard(const TempDirGuard&) = delete;
  TempDirGuard& operator=(const TempDirGuard&) = delete;
};

}  // namespace

// ===========================================================================
// Regeneration (no-op unless SCANENGINE_REGEN_GOLDEN is set — see file header)
// ===========================================================================

TEST_CASE("e2/regenerate_golden_fixtures") {
  if (std::getenv("SCANENGINE_REGEN_GOLDEN") == nullptr) {
    MESSAGE("SKIPPED (by design): set SCANENGINE_REGEN_GOLDEN=1 to (re)write "
            "tests/integration/data/golden_{d6,mid360}.bin");
    return;
  }
  const auto d6_bytes = build_golden_d6_bytes();
  const auto mid360_bytes = build_golden_mid360_bytes();
  REQUIRE(write_file(data_path("golden_d6.bin"), d6_bytes));
  REQUIRE(write_file(data_path("golden_mid360.bin"), mid360_bytes));
  MESSAGE("wrote golden_d6.bin (" << d6_bytes.size() << " bytes) and golden_mid360.bin ("
                                  << mid360_bytes.size() << " bytes)");
}

// ===========================================================================
// D6 — committed golden byte stream
// ===========================================================================

TEST_CASE("e2/d6_replay_golden_is_byte_stable") {
  // The committed file must equal what the builder produces today. If this
  // ever fails, either the golden file bit-rotted (should not happen — it is
  // committed, not generated per-run) or packet_builder.h's encoding changed
  // underneath every D6 test in the repo, which is worth knowing loudly.
  std::vector<std::uint8_t> committed;
  REQUIRE(read_file(data_path("golden_d6.bin"), &committed));
  CHECK(committed == build_golden_d6_bytes());

  EventBus bus;
  PageStore points(PageStoreConfig{4096, 8});
  DriverContext ctx;
  ctx.bus = &bus;
  ctx.points = &points;

  D6Config cfg;
  cfg.send_start_stop_commands = false;
  cfg.max_batch_points = 4096;  // one flush at stop(), so page contents are deterministic
  D6Driver driver(1, cfg, ctx);
  REQUIRE(driver.start().ok());
  REQUIRE(driver.push_bytes(ByteSpan(committed.data(), committed.size()), TimePoint{0}).ok());
  REQUIRE(driver.stop().ok());

  const d6::Stats stats = driver.parser_stats();
  MESSAGE("d6 golden: packets_ok " << stats.packets_ok << ", bad_checksum "
                                   << stats.packets_bad_checksum << ", malformed "
                                   << stats.packets_malformed << ", points " << stats.points
                                   << ", rotations " << stats.rotations);

  // 6 revolution packets (20 samples each) + 1 start packet = 7 packets, all
  // well-formed with a valid vendor checksum (build_revolution's default).
  CHECK(stats.packets_ok == 7);
  CHECK(stats.packets_bad_checksum == 0);
  CHECK(stats.packets_malformed == 0);
  CHECK(stats.checksum_pass_rate() == doctest::Approx(1.0));
  // 6*20 revolution samples + 1 start-packet sample = 121 decoded points, all
  // non-zero range so none are dropped by drop_zero_range_points.
  CHECK(stats.points == 121);
  CHECK(stats.points_zero_range == 0);

  const auto ids = points.page_ids();
  REQUIRE(ids.size() == 1);
  const PageView v = points.page_view(ids[0]);
  REQUIRE(v.valid());
  CHECK(v.stream == StreamId::kLidarD6);
  REQUIRE(v.count == 121);

  MESSAGE("d6 golden: first (" << v.data[0].x << ", " << v.data[0].y << "), last ("
                               << v.data[v.count - 1].x << ", " << v.data[v.count - 1].y << ")");

  // The start packet's own sample (angle 0, 1.000 m): x = 0, y = 1.
  CHECK(v.data[0].x == doctest::Approx(0.0f).epsilon(1e-4));
  CHECK(v.data[0].y == doctest::Approx(1.0f).epsilon(1e-4));
  // The revolution's LAST sample is 1/120th of a turn before closing back to
  // 360 deg, i.e. angle = 360 - 360/120 = 357 deg exactly (120 = 6*20).
  //
  // ROUND 9 item 34: this x flipped sign, from -0.05234 to +0.05234. It is the
  // golden pin on the fan-frame handedness (d6_fan.h): x = -d*sin(357 deg) =
  // +0.05234. If a future change flips the sweep back, this line fails first.
  CHECK(v.data[v.count - 1].x == doctest::Approx(0.05234f).epsilon(1e-3));
  CHECK(v.data[v.count - 1].y == doctest::Approx(0.99863f).epsilon(1e-3));
}

// ===========================================================================
// Mid-360 — committed golden datagram sequence
// ===========================================================================

TEST_CASE("e2/mid360_inject_golden_is_byte_stable") {
  std::vector<std::uint8_t> committed;
  REQUIRE(read_file(data_path("golden_mid360.bin"), &committed));
  CHECK(committed == build_golden_mid360_bytes());

  EventBus bus;
  PageStore points(PageStoreConfig{4096, 8});
  DriverContext ctx;
  ctx.bus = &bus;
  ctx.points = &points;

  Mid360Config cfg;
  cfg.backend = Mid360Backend::kInject;
  cfg.internal_supervisor_thread = false;
  cfg.live_points_per_sec = 0;              // no decimation: count every point
  cfg.max_batch_points = 8 * mid360::kPointsPerPacket;  // one flush, deterministic page contents
  Mid360Driver driver(1, cfg, ctx);
  REQUIRE(driver.start().ok());

  std::size_t datagrams = 0;
  REQUIRE(feed_mid360_datagrams(&driver, committed, TimePoint{2'000'000'000}, &datagrams));
  REQUIRE(driver.stop().ok());  // flushes the remaining batch, same as D6

  const Mid360Stats st = driver.stats();
  MESSAGE("mid360 golden: datagrams " << datagrams << ", point_packets " << st.point_packets
                                      << ", imu_packets " << st.imu_packets
                                      << ", points_received " << st.points_received
                                      << ", points_kept " << st.points_kept
                                      << ", points_appended " << st.points_appended
                                      << ", bad_packets " << st.bad_packets);

  CHECK(datagrams == 10);  // 8 point + 2 imu
  CHECK(st.point_packets == 8);
  CHECK(st.imu_packets == 2);
  CHECK(st.bad_packets == 0);
  CHECK(st.points_received == 8 * mid360::kPointsPerPacket);
  CHECK(st.points_kept == 8 * mid360::kPointsPerPacket);   // tag 0, in range: nothing filtered
  CHECK(st.points_appended == 8 * mid360::kPointsPerPacket);
  CHECK(st.packets_lost == 0);

  const auto ids = points.page_ids();
  REQUIRE(ids.size() == 1);
  const PageView v = points.page_view(ids[0]);
  REQUIRE(v.valid());
  CHECK(v.stream == StreamId::kLidarMid360);
  REQUIRE(v.count == 8 * mid360::kPointsPerPacket);

  MESSAGE("mid360 golden: first (" << v.data[0].x << ", " << v.data[0].y << ", " << v.data[0].z
                                   << "), last (" << v.data[v.count - 1].x << ", "
                                   << v.data[v.count - 1].y << ", " << v.data[v.count - 1].z
                                   << ")");

  // First datagram's first point: x0 = 1000 mm -> 1.000 m, y = 3.000 m, z = 1.200 m.
  CHECK(v.data[0].x == doctest::Approx(1.000f));
  CHECK(v.data[0].y == doctest::Approx(3.000f));
  CHECK(v.data[0].z == doctest::Approx(1.200f));
  // Last datagram (k=7, x0 = 1000 + 700 = 1700 mm) last sample (i=95):
  // x = 1700 + 95*10 = 2650 mm = 2.650 m.
  const std::size_t last = v.count - 1;
  CHECK(v.data[last].x == doctest::Approx(2.650f));
  CHECK(v.data[last].y == doctest::Approx(3.000f));
  CHECK(v.data[last].z == doctest::Approx(1.200f));

  // IMU never reaches the PageStore (mid360_driver.h's contract); drain_imu()
  // is the only way to see the two samples this golden file carries.
  Mid360ImuSample imu[4]{};
  const std::size_t n_imu = driver.drain_imu(imu, 4);
  REQUIRE(n_imu == 2);
  CHECK(imu[0].gyro[0] == doctest::Approx(0.01f));
  CHECK(imu[0].acc[2] == doctest::Approx(1.0f));
  CHECK(imu[1].gyro[0] == doctest::Approx(-0.02f));
  CHECK(imu[1].acc[2] == doctest::Approx(0.98f));
}

// ===========================================================================
// The CC-BY real capture — runtime skip-unless-present, per FIXTURES.md
// ===========================================================================

TEST_CASE("e2/real_capture_lio_post_matches_A6_A7_numbers") {
  const std::string src = find_ccby_fixture();
  if (src.empty()) {
    MESSAGE("SKIPPED: outdoor_imu_ccby_6s.livoxdump not found (set SCANENGINE_LIVOXDUMP, "
            "or run from a checkout that has spikes/s2-mid360-sim/fixtures/ — see "
            "spikes/s2-mid360-sim/FIXTURES.md; this is the one CC-BY-4.0 fixture that IS "
            "committed, so a normal checkout should always find it)");
    return;
  }

  const std::string dir = make_temp_dir("e2real");
  TempDirGuard guard(dir);
  std::uint64_t records = 0;
  REQUIRE(transcode_livoxdump(src, dir, &records));
  MESSAGE("e2 real: transcoded " << records << " datagrams from " << src);
  REQUIRE(records > 10000);

  // Same live-decimation config docs/A7-post.md §6.3 measured — this is an
  // integration smoke test re-checking A6/A7's own documented numbers still
  // hold, not a re-derivation of them from scratch.
  post::PostConfig cfg;
  cfg.lio.live_points_per_sec = 40000;
  cfg.lio.max_points_per_scan = 12000;
  cfg.lio.max_range_m = 60.0f;
  cfg.keyframe_voxel_m = 0.3;
  cfg.max_points_per_keyframe = 5000;
  cfg.dedup.voxel_size_m = 0.10;
  cfg.outlier.enabled = true;
  cfg.outlier.std_dev_mul = 2.0;

  post::PostSlamPipeline a(cfg);
  REQUIRE(a.run(dir).ok());
  const post::PostStats& sa = a.stats();

  MESSAGE("e2 real: scans " << sa.lio.scans << ", |g| " << sa.lio.gravity_m_s2 << ", path "
                            << sa.trajectory_length_m << " m, loops " << sa.loops_accepted
                            << ", final points " << sa.final_points);

  // docs/A6-lio.md §7.2 / docs/A7-post.md §6.3: |g| = 9.816 m/s^2, path length
  // 32.39-32.40 m, measured on this exact fixture with this exact config.
  // Tolerances are generous (this is a synthetic-baseline sanity check, not a
  // bit-for-bit re-measurement across compiler/toolchain versions) but tight
  // enough that a real regression — a Jacobian sign flip, a unit conversion
  // bug, a filter default change — would fail it.
  CHECK(sa.lio.initialized);
  CHECK_FALSE(sa.lio.diverged);
  CHECK(sa.lio.gravity_m_s2 == doctest::Approx(9.816).epsilon(0.02));  // within ~0.2 m/s^2
  CHECK(sa.trajectory_length_m == doctest::Approx(32.4).epsilon(0.05));  // within ~5%
  CHECK(sa.loops_accepted == 0);  // a straight 6 s drive revisits nothing (A7 §6.3)
  CHECK(sa.final_points > 0);

  // Determinism: the same fixture through the same pipeline twice. This is
  // the "+post" half of "E2 builds on S4's checklist" — A7 already proves
  // determinism for its own synthetic fixture (post/two_runs_are_bit_identical);
  // this repeats the cheaper half of that claim (scalar stats, not a full
  // memcmp of the final cloud) against the real capture as an integration
  // check owned outside slam/post/.
  post::PostSlamPipeline b(cfg);
  REQUIRE(b.run(dir).ok());
  const post::PostStats& sb = b.stats();
  CHECK(sa.lio.gravity_m_s2 == sb.lio.gravity_m_s2);
  CHECK(sa.trajectory_length_m == sb.trajectory_length_m);
  CHECK(sa.final_points == sb.final_points);
  CHECK(sa.graph.final_chi2 == sb.graph.final_chi2);
}
